import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '@/context/auth-context';
import { colors } from '@/theme';

export function BrandHeader({ showLikes = true }: { showLikes?: boolean }) {
  const { user } = useAuth();
  const initial = (user?.user_metadata?.display_name || user?.email || 'A').charAt(0).toUpperCase();
  return <View style={styles.row}><Pressable accessibilityRole="button" accessibilityLabel="Home" onPress={() => router.replace('/preferences')} style={styles.brand}><View style={styles.dot} /><Text style={styles.logo}>CRAVE</Text></Pressable><View style={styles.actions}><Pressable accessibilityRole="button" accessibilityLabel="Craving rooms" onPress={() => router.push('/friends')} style={styles.saved}><Text style={styles.people}>☺</Text></Pressable>{showLikes && <Pressable accessibilityRole="button" accessibilityLabel="Saved dishes" onPress={() => router.push('/likes')} style={styles.saved}><Text style={styles.heart}>♥</Text></Pressable>}<Pressable accessibilityRole="button" accessibilityLabel={user ? 'Account' : 'Sign in'} onPress={() => router.push(user ? '/account' : '/auth')} style={[styles.saved, user && styles.account]}><Text style={[styles.accountText, user && styles.accountTextActive]}>{user ? initial : '♙'}</Text></Pressable></View></View>;
}
const styles = StyleSheet.create({ row: { height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, brand: { flexDirection: 'row', alignItems: 'center', gap: 8 }, dot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.coral }, logo: { color: colors.charcoal, fontWeight: '900', letterSpacing: 2.7, fontSize: 15 }, actions: { flexDirection: 'row', gap: 8 }, saved: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line }, account: { backgroundColor: colors.charcoal, borderColor: colors.charcoal }, heart: { color: colors.coral, fontSize: 20, marginTop: -1 }, people: { color: colors.sage, fontSize: 20, marginTop: -1 }, accountText: { color: colors.charcoal, fontWeight: '900', fontSize: 17 }, accountTextActive: { color: colors.white } });
