/* eslint-disable react-hooks/refs, react-hooks/exhaustive-deps */
// React Native Animated values intentionally live in refs so gestures do not trigger renders.
import { Image } from 'expo-image';
import { LinearGradient } from 'expo-linear-gradient';
import { useMemo, useRef } from 'react';
import { Animated, Dimensions, PanResponder, StyleSheet, Text, View } from 'react-native';
import { colors, fonts, radius, shadow, spacing } from '@/theme';
import { Dish, SwipeChoice } from '@/types';

const screenWidth = Dimensions.get('window').width;
const threshold = Math.min(120, screenWidth * 0.28);
export function SwipeCard({ dish, onSwipe }: { dish: Dish; onSwipe: (choice: SwipeChoice) => void }) {
  const position = useRef(new Animated.ValueXY()).current;
  const rotate = position.x.interpolate({ inputRange: [-screenWidth, 0, screenWidth], outputRange: ['-14deg', '0deg', '14deg'] });
  const likeOpacity = position.x.interpolate({ inputRange: [0, threshold], outputRange: [0, 1], extrapolate: 'clamp' });
  const passOpacity = position.x.interpolate({ inputRange: [-threshold, 0], outputRange: [1, 0], extrapolate: 'clamp' });
  const finish = (choice: SwipeChoice) => Animated.timing(position, { toValue: { x: choice === 'like' ? screenWidth * 1.4 : -screenWidth * 1.4, y: 25 }, duration: 240, useNativeDriver: true }).start(() => onSwipe(choice));
  const pan = useMemo(() => PanResponder.create({ onMoveShouldSetPanResponder: (_, g) => Math.abs(g.dx) > 7, onPanResponderMove: Animated.event([null, { dx: position.x, dy: position.y }], { useNativeDriver: false }), onPanResponderRelease: (_, g) => { if (g.dx > threshold) finish('like'); else if (g.dx < -threshold) finish('pass'); else Animated.spring(position, { toValue: { x: 0, y: 0 }, friction: 5, useNativeDriver: true }).start(); } }), [dish.id]);
  return <Animated.View {...pan.panHandlers} style={[styles.card, { transform: [{ translateX: position.x }, { translateY: position.y }, { rotate }] }]}><Image source={dish.image} style={StyleSheet.absoluteFill} contentFit="cover" transition={250} /><LinearGradient colors={['transparent','rgba(17,14,12,0.12)','rgba(17,14,12,0.9)']} locations={[0.25,0.55,1]} style={StyleSheet.absoluteFill} /><Animated.View style={[styles.stamp, styles.yum, { opacity: likeOpacity }]}><Text style={styles.yumText}>YUM</Text></Animated.View><Animated.View style={[styles.stamp, styles.pass, { opacity: passOpacity }]}><Text style={styles.passText}>PASS</Text></Animated.View><View style={styles.info}><View style={styles.meta}><Text style={styles.cuisine}>{dish.cuisine.toUpperCase()}</Text><Text style={styles.dot}>•</Text><Text style={styles.metaText}>{'$'.repeat(dish.price)}</Text><Text style={styles.dot}>•</Text><Text style={styles.metaText}>{dish.time} min</Text></View><Text style={styles.name}>{dish.name}</Text><Text style={styles.description}>{dish.description}</Text><View style={styles.tags}>{dish.tags.slice(0, 3).map((tag) => <View key={tag} style={styles.tag}><Text style={styles.tagText}>{tag}</Text></View>)}</View></View></Animated.View>;
}
const styles = StyleSheet.create({ card: { position: 'absolute', width: '100%', height: '100%', borderRadius: radius.lg, overflow: 'hidden', backgroundColor: colors.charcoal, ...shadow }, info: { position: 'absolute', left: spacing.lg, right: spacing.lg, bottom: spacing.lg }, meta: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 7 }, cuisine: { color: '#FFD2C7', fontWeight: '900', fontSize: 10, letterSpacing: 1.5 }, dot: { color: 'rgba(255,255,255,.45)' }, metaText: { color: 'rgba(255,255,255,.8)', fontSize: 12, fontWeight: '600' }, name: { color: colors.white, fontSize: 34, lineHeight: 38, fontFamily: fonts.serif, fontWeight: '700' }, description: { color: 'rgba(255,255,255,.78)', fontSize: 13, lineHeight: 19, marginTop: 7 }, tags: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 13 }, tag: { backgroundColor: 'rgba(255,255,255,.16)', paddingHorizontal: 10, paddingVertical: 6, borderRadius: radius.full, borderWidth: 1, borderColor: 'rgba(255,255,255,.16)' }, tagText: { color: colors.white, fontSize: 11, fontWeight: '700' }, stamp: { position: 'absolute', top: 30, paddingHorizontal: 14, paddingVertical: 8, borderWidth: 3, borderRadius: 9, transform: [{ rotate: '-9deg' }] }, yum: { left: 24, borderColor: '#D5FFB9' }, pass: { right: 24, borderColor: '#FFD4CC', transform: [{ rotate: '9deg' }] }, yumText: { color: '#D5FFB9', fontWeight: '900', fontSize: 24, letterSpacing: 2 }, passText: { color: '#FFD4CC', fontWeight: '900', fontSize: 22, letterSpacing: 2 } });
